### PR TITLE
Removed need for view snapshot and converted to a UIWindow based layout

### PR DESCRIPTION
**Pull request by jinthagerman**
This is a fairly large change in direction for the codebase. I don't really expect it to be merged, but I thought someone might be interested in the changes. 

Basically, I have removed the need for a snapshot of the view and I am animating the target view's layer instead. The layer is set to rasterise before animating and this is reversed after the semimodal is dismissed.

I have also shifted the code to use UIWindows for layout and layering as I believe this is a simpler and more robust solution.

### CODE REVIEW

**Comment by kentnguyen** [comment]
Thanks for the contribution. I'll review this approach and see if it fits the coming changes I'm going to make.

**Comment by lexrus** [comment]
Awesome! But buttons in the custom view does not work.

**Comment by mRs-** [comment]
Is this Project still living? It will be really good not to create a screenshot because of animations in the background-view.

**Comment by kentnguyen** [comment]
I have reviewed the code and there are quite a number of conflicts with the latest development so I would want to keep the current implementation. As of now I think it fits most of the use cases and (I guess) it is less resource-intensive to render static screenshot instead of a 'live' one.

**Pull request closed without merging**
